# Generated by Django 6.0.4 on 2026-05-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jabatan',
            field=models.CharField(choices=[('HRD', 'HRD'), ('Staff', 'Staff')], default='HRD', max_length=50),
            preserve_default=False,
        ),
    ]
