# Generated by Django 6.0.4 on 2026-05-01 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_jabatan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='jabatan',
        ),
    ]
