# Generated by Django 6.0.4 on 2026-05-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_jabatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('kepala_gudang', 'Kepala Gudang'), ('staff_gudang', 'Staff Gudang')], max_length=20),
        ),
    ]
