# Generated by Django 6.0.4 on 2026-05-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('nik', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telepon', models.CharField(max_length=50)),
                ('departemen', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('jabatan', models.CharField(choices=[('HRD', 'HRD'), ('Staff Gudang', 'Staff Gudang'), ('Karyawan Kontrak', 'Karyawan Kontrak'), ('Karyawan Tetap', 'Karyawan Tetap')], max_length=50)),
            ],
        ),
    ]
