# Generated by Django 6.0.4 on 2026-05-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_karyawan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='jabatan',
            field=models.CharField(choices=[('HRD', 'HRD'), ('Staff Gudang', 'Staff Gudang')], max_length=50),
        ),
    ]
