# Generated by Django 6.0.4 on 2026-05-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_karyawan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='jabatan',
            field=models.CharField(choices=[('HRD', 'HRD'), ('kepala_gudang', 'Kepala Gudang'), ('staff_gudang', 'Staff Gudang')], max_length=50),
        ),
    ]
