# Generated by Django 6.0.4 on 2026-05-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_karyawan_jabatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kode_barang',
            field=models.CharField(default='B0001', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='karyawan',
            unique_together={('nik', 'nama', 'email')},
        ),
    ]
