# Generated by Django 6.0.4 on 2026-05-02 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_product_kode_barang_alter_karyawan_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(choices=[('HRD', 'HRD'), ('kepala_gudang', 'Kepala Gudang'), ('staff_gudang', 'Staff Gudang')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='jabatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.jabatan'),
        ),
    ]
