# Generated by Django 6.0.4 on 2026-05-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_jabatan_alter_karyawan_jabatan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karyawan',
            name='departemen',
        ),
        migrations.AddField(
            model_name='jabatan',
            name='departemen',
            field=models.CharField(choices=[('staff_hrd', 'Staff HRD'), ('gudang', 'Gudang')], default='gudang', max_length=100),
            preserve_default=False,
        ),
    ]
