# Generated by Django 6.0.4 on 2026-05-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_karyawan_departemen_jabatan_departemen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jabatan',
            name='departemen',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jabatan',
            name='jabatan',
            field=models.CharField(max_length=50),
        ),
    ]
