# Generated by Django 6.0.4 on 2026-05-02 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_jabatan_departemen_alter_jabatan_jabatan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departemen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departemen', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='jabatan',
            name='departemen',
        ),
        migrations.AddField(
            model_name='karyawan',
            name='departemen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.departemen'),
            preserve_default=False,
        ),
    ]
