# Generated by Django 6.0.4 on 2026-05-09 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='note',
        ),
        migrations.AddField(
            model_name='transaction',
            name='kode_barang',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='kode_barang',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
