# Generated by Django 6.0.4 on 2026-05-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_transaction_note_transaction_kode_barang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='suplier',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
