# Generated by Django 6.0.4 on 2026-05-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_product_suplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='note',
            field=models.CharField(default='hello', max_length=255),
            preserve_default=False,
        ),
    ]
